use CS6_3
SELECT * FROM PROPIETARIO
SELECT * FROM VEHICULO
/// Tabla Vehiculo ///

CREATE TABLE PROPIETARIO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DNI NVARCHAR(10) UNIQUE,
    NOMBRES NVARCHAR(100),
    APELLIDOS NVARCHAR(100),
    CORREO NVARCHAR(100),
    TELEFONO NVARCHAR(20),
    DIRECCION NVARCHAR(200)
);
/// Procedimientos de Propietario///

CREATE PROCEDURE InsertarPropietario
    @DNI NVARCHAR(10),
    @NOMBRES NVARCHAR(100),
    @APELLIDOS NVARCHAR(100),
    @CORREO NVARCHAR(100),
    @TELEFONO NVARCHAR(20),
    @DIRECCION NVARCHAR(200)
AS
BEGIN
    INSERT INTO PROPIETARIO (DNI, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION)
    VALUES (@DNI, @NOMBRES, @APELLIDOS, @CORREO, @TELEFONO, @DIRECCION);
END



CREATE PROCEDURE ModificarPropietario
    @DNI NVARCHAR(10),
    @NOMBRES NVARCHAR(100),
    @APELLIDOS NVARCHAR(100),
    @CORREO NVARCHAR(100),
    @TELEFONO NVARCHAR(20),
    @DIRECCION NVARCHAR(200)
AS
BEGIN
    UPDATE PROPIETARIO
    SET NOMBRES = @NOMBRES,
        APELLIDOS = @APELLIDOS,
        CORREO = @CORREO,
        TELEFONO = @TELEFONO,
        DIRECCION = @DIRECCION
    WHERE DNI = @DNI;
END



CREATE PROCEDURE EliminarPropietario
    @DNI NVARCHAR(10)
AS
BEGIN
    DELETE FROM PROPIETARIO
    WHERE DNI = @DNI;
END



CREATE PROCEDURE BuscarPropietarioPorDNI
    @DNI NVARCHAR(10)
AS
BEGIN
    SELECT DNI, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION
    FROM PROPIETARIO
    WHERE DNI = @DNI;
END

CREATE TABLE VEHICULO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PLACA NVARCHAR(8) UNIQUE,
    VALOR DECIMAL(10,2), 
    AÑO INT,
    CILINDRAJE INT, 
    MODELO NVARCHAR(50), 
    COLOR NVARCHAR(100),
    ID_PROPIETARIO INT FOREIGN KEY REFERENCES PROPIETARIO(ID)
);
-- Procedimiento para insertar un vehículo
CREATE PROCEDURE InsertarVehiculo
    @PLACA NVARCHAR(8),
    @VALOR DECIMAL(10,2),
    @AÑO INT,
    @CILINDRAJE INT,
    @MODELO NVARCHAR(50),
    @COLOR NVARCHAR(100),
    @DNI_PROPIETARIO NVARCHAR(10) -- DNI del propietario
AS
BEGIN
    DECLARE @ID_PROPIETARIO INT

    -- Obtener el ID del propietario usando el DNI proporcionado
    SELECT @ID_PROPIETARIO = ID FROM PROPIETARIO WHERE DNI = @DNI_PROPIETARIO

    -- Insertar el vehículo con el ID del propietario obtenido
    INSERT INTO VEHICULO (PLACA, VALOR, AÑO, CILINDRAJE, MODELO, COLOR, ID_PROPIETARIO)
    VALUES (@PLACA, @VALOR, @AÑO, @CILINDRAJE, @MODELO, @COLOR, @ID_PROPIETARIO);
END


-- Procedimiento para modificar un vehículo
CREATE PROCEDURE ModificarVehiculo
    @PLACA NVARCHAR(8),
    @VALOR DECIMAL(10,2),
    @AÑO INT,
    @CILINDRAJE INT,
    @MODELO NVARCHAR(50),
    @COLOR NVARCHAR(100),
    @DNI_PROPIETARIO NVARCHAR(10) -- DNI del propietario
AS
BEGIN
    DECLARE @ID_PROPIETARIO INT

    -- Obtener el ID del propietario usando el DNI proporcionado
    SELECT @ID_PROPIETARIO = ID FROM PROPIETARIO WHERE DNI = @DNI_PROPIETARIO

    -- Modificar el vehículo con el ID del propietario obtenido
    UPDATE VEHICULO
    SET PLACA = @PLACA,
        VALOR = @VALOR,
        AÑO = @AÑO,
        CILINDRAJE = @CILINDRAJE,
        MODELO = @MODELO,
        COLOR = @COLOR,
        ID_PROPIETARIO = @ID_PROPIETARIO
    WHERE PLACA = @PLACA;
END


-- Procedimiento para eliminar un vehículo
CREATE PROCEDURE EliminarVehiculo
    @PLACA NVARCHAR(8)
AS
BEGIN
    DELETE FROM VEHICULO
    WHERE PLACA = @PLACA;
END


-- Procedimiento para buscar un vehículo por su placa
CREATE PROCEDURE BuscarVehiculoPorPlaca
    @PLACA NVARCHAR(8)
AS
BEGIN
    SELECT V.PLACA, V.VALOR, V.AÑO, V.CILINDRAJE, V.MODELO, V.COLOR, P.DNI, P.NOMBRES, P.APELLIDOS, P.CORREO, P.TELEFONO, P.DIRECCION
    FROM VEHICULO V
    INNER JOIN PROPIETARIO P ON V.ID_PROPIETARIO = P.ID
    WHERE V.PLACA = @PLACA;
END

CREATE PROCEDURE BuscarPropietarioPorDNINuevo
    @DNI NVARCHAR(10)
AS
BEGIN
    SELECT DNI, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION
    FROM PROPIETARIO
    WHERE DNI = @DNI;
END
